(function(b,e){function p(){return!1}function y(c){var a=e.innerHeight/c.height,b=e.innerWidth/c.width,a=a>b?b:a;c.b&&a>c.b&&(a=c.b);c.c&&a<c.c&&(a=c.c);return a}function q(a,b){var c=" rotateX("+a.x+"deg) ",d=" rotateY("+a.y+"deg) ",e=" rotateZ("+a.z+"deg) ";return b?e+d+c:c+d+e}function a(a){return" translate3d("+a.x+"px,"+a.y+"px,"+a.z+"px) "}function d(a,d,e){var c=b.createEvent("CustomEvent");c.initCustomEvent(d,!0,!0,e);a.dispatchEvent(c)}function t(a){a=a||b;return[].slice.call(a.querySelectorAll(".step"))}
function I(){var a;a=a||b;return a.querySelector("meta[name='viewport']")}function l(a,b){return isNaN(a)?b||0:Number(a)}function u(a,b){var d,c;for(d in b)b.hasOwnProperty(d)&&(c=z(d),null!==c&&(a.style[c]=b[d]))}var z=function(){var a=b.createElement("dummy").style,d=["Webkit","Moz","O","ms","Khtml"],e={};return function(b){if("undefined"===typeof e[b]){var c=b.charAt(0).toUpperCase()+b.substr(1),c=(b+" "+d.join(c+" ")+c).split(" ");e[b]=null;for(var k in c)if(void 0!==a[c[k]]){e[b]=c[k];break}}return e[b]}}(),
n=b.body,E=navigator.userAgent.toLowerCase(),F=null!==z("perspective")&&n.classList&&n.dataset&&-1===E.search(/(iphone)|(ipod)|(android)/);F?(n.classList.remove("impress-not-supported"),n.classList.add("impress-supported")):n.className+=" impress-not-supported ";var A={};(e.j=function(c){function w(h,b){if(!G||!(h=z(h)))return!1;e.scrollTo(0,0);var f=D["impress-"+h.id];k&&(k.classList.remove("active"),n.classList.remove("impress-on-"+k.id));h.classList.add("active");n.classList.add("impress-on-"+
h.id);var f={rotate:{x:-f.rotate.x,y:-f.rotate.y,z:-f.rotate.z},translate:{x:-f.translate.x,y:-f.translate.y,z:-f.translate.z},scale:1/f.scale},c=f.scale>=r.scale;b=l(b,v.transitionDuration);var g=b/2;h===k&&(x=y(v));var t=f.scale*x;k&&k!==h&&B===k&&(d(k,"impress:stepleave"),B=null);u(m,{perspective:v.perspective/t+"px",transform:" scale("+t+") ",transitionDuration:b+"ms",transitionDelay:(c?g:0)+"ms"});u(C,{transform:q(f.rotate,!0)+a(f.translate),transitionDuration:b+"ms",transitionDelay:(c?0:g)+
"ms"});if(r.scale===f.scale||r.rotate.x===f.rotate.x&&r.rotate.y===f.rotate.y&&r.rotate.z===f.rotate.z&&r.translate.x===f.translate.x&&r.translate.y===f.translate.y&&r.translate.z===f.translate.z)g=0;r=f;k=h;e.clearTimeout(H);H=e.setTimeout(function(){var a=k;B!==a&&(d(a,"impress:stepenter"),B=a)},b+g);return h}function z(a){"number"===typeof a?a=0>a?g[g.length+a]:g[a]:"string"===typeof a&&(a=b.getElementById(a));return a&&a.id&&D["impress-"+a.id]?a:null}function E(h,b){var c=h.dataset,c={translate:{x:l(c.x),
y:l(c.y),z:l(c.z)},rotate:{x:l(c.l),y:l(c.m),z:l(c.o||c.rotate)},scale:l(c.scale,1),i:h};h.id||(h.id="step-"+(b+1));D["impress-"+h.id]=c;u(h,{position:"absolute",transform:"translate(-50%,-50%)"+a(c.translate)+q(c.rotate)+(" scale("+c.scale+") "),transformStyle:"preserve-3d"})}if(!F)return{h:p,a:p,f:p,next:p};c=c||"impress";if(A["impress-root-"+c])return A["impress-root-"+c];var D={},k=null,r=null,g=null,v=null,x=null,m=b.getElementById(c),C=b.createElement("div"),G=!1,B=null,H=null;m.addEventListener("impress:init",
function(){g.forEach(function(a){a.classList.add("future")});m.addEventListener("impress:stepenter",function(a){a.target.classList.remove("past");a.target.classList.remove("future");a.target.classList.add("present")},!1);m.addEventListener("impress:stepleave",function(a){a.target.classList.remove("present");a.target.classList.add("past")},!1)},!1);m.addEventListener("impress:init",function(){var a="";m.addEventListener("impress:stepenter",function(b){e.location.hash=a="#/"+b.target.id},!1);e.addEventListener("hashchange",
function(){e.location.hash!==a&&w(b.getElementById(e.location.hash.replace(/^#\/?/,"")))},!1);w(b.getElementById(e.location.hash.replace(/^#\/?/,""))||g[0],0)},!1);n.classList.add("impress-disabled");return A["impress-root-"+c]={h:function(){if(!G){var a=I()||b.createElement("meta");a.content="width=device-width, minimum-scale=1, maximum-scale=1, user-scalable=no";a.parentNode!==b.head&&(a.name="viewport",b.head.appendChild(a));a=m.dataset;v={width:l(a.width,1024),height:l(a.height,768),b:l(a.b,1),
c:l(a.c,0),perspective:l(a.perspective,1E3),transitionDuration:l(a.transitionDuration,1E3)};x=y(v);[].slice.call(m.childNodes).forEach(function(a){C.appendChild(a)});m.appendChild(C);b.documentElement.style.height="100%";u(n,{height:"100%",overflow:"hidden"});a={position:"absolute",transformOrigin:"top left",transition:"all 0s ease-in-out",transformStyle:"preserve-3d"};u(m,a);u(m,{top:"50%",left:"50%",perspective:v.perspective/x+"px",transform:" scale("+x+") "});u(C,a);n.classList.remove("impress-disabled");
n.classList.add("impress-enabled");g=t(m);g.forEach(E);r={translate:{x:0,y:0,z:0},rotate:{x:0,y:0,z:0},scale:1};G=!0;d(m,"impress:init",{g:A["impress-root-"+c]})}},a:w,next:function(){var a=g.indexOf(k)+1,a=a<g.length?g[a]:g[0];return w(a)},f:function(){var a=g.indexOf(k)-1,a=0<=a?g[a]:g[g.length-1];return w(a)}}}).s=F})(document,window);
(function(b,e){function p(b){var e=null;return function(){var a=this,d=arguments;clearTimeout(e);e=setTimeout(function(){b.apply(a,d)},250)}}b.addEventListener("impress:init",function(y){var q=y.detail.g;b.addEventListener("keydown",function(a){(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&40>=a.keyCode)&&a.preventDefault()},!1);b.addEventListener("keyup",function(a){if(!(a.shiftKey||a.altKey||a.ctrlKey||a.metaKey)&&(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&40>=a.keyCode)){switch(a.keyCode){case 33:case 37:case 38:q.f();
break;case 9:case 32:case 34:case 39:case 40:q.next()}a.preventDefault()}},!1);b.addEventListener("click",function(a){for(var d=a.target;"A"!==d.tagName&&d!==b.documentElement;)d=d.parentNode;if("A"===d.tagName){var e=d.getAttribute("href");e&&"#"===e[0]&&(d=b.getElementById(e.slice(1)))}q.a(d)&&(a.stopImmediatePropagation(),a.preventDefault())},!1);b.addEventListener("click",function(a){for(var d=a.target;(!d.classList.contains("step")||d.classList.contains("active"))&&d!==b.documentElement;)d=d.parentNode;
q.a(d)&&a.preventDefault()},!1);b.addEventListener("touchstart",function(a){if(1===a.touches.length){var b=a.touches[0].clientX,t=.3*e.innerWidth,p=null;b<t?p=q.f():b>e.innerWidth-t&&(p=q.next());p&&a.preventDefault()}},!1);e.addEventListener("resize",p(function(){q.a(b.querySelector(".step.active"),500)}),!1)},!1)})(document,window);
