(function(b,h){var p=function(){var f=b.createElement("dummy").style,a=["Webkit","Moz","O","ms","Khtml"],l={};return function(e){if("undefined"===typeof l[e]){var b=e.charAt(0).toUpperCase()+e.substr(1),b=(e+" "+a.join(b+" ")+b).split(" ");l[e]=null;for(var d in b)if(void 0!==f[b[d]]){l[e]=b[d];break}}return l[e]}}(),m=function(f,e){var a,b;for(a in e)e.hasOwnProperty(a)&&(b=p(a),null!==b&&(f.style[b]=e[a]));return f},d=function(a,e){return isNaN(a)?e||0:Number(a)},a=function(a,e){e=e||b;return e.querySelector(a)},
g=function(a,e){e=e||b;return[].slice.call(e.querySelectorAll(a))},z=function(a,e,d){var f=b.createEvent("CustomEvent");f.initCustomEvent(e,!0,!0,d);a.dispatchEvent(f)},D=function(a){return" translate3d("+a.x+"px,"+a.y+"px,"+a.z+"px) "},E=function(a,e){var b=" rotateX("+a.x+"deg) ",d=" rotateY("+a.y+"deg) ",f=" rotateZ("+a.z+"deg) ";return e?f+d+b:b+d+f},F=function(a){var b=h.innerHeight/a.height,d=h.innerWidth/a.width,b=b>d?d:b;a.maxScale&&b>a.maxScale&&(b=a.maxScale);a.minScale&&b<a.minScale&&(b=
a.minScale);return b},q=b.body,A=navigator.userAgent.toLowerCase(),B=null!==p("perspective")&&q.classList&&q.dataset&&-1===A.search(/(iphone)|(ipod)|(android)/);B?(q.classList.remove("impress-not-supported"),q.classList.add("impress-supported")):q.className+=" impress-not-supported ";var w={},x=function(){return!1};(h.impress=function(f){if(!B)return{init:x,"goto":x,prev:x,next:x};f=f||"impress";if(w["impress-root-"+f])return w["impress-root-"+f];var e={},l=null,r=null,k=null,t=null,u=null,n=b.getElementById(f),
p=b.createElement("div"),C=!1,y=null,A=function(a,b){var c=a.dataset,c={translate:{x:d(c.x),y:d(c.y),z:d(c.z)},rotate:{x:d(c.rotateX),y:d(c.rotateY),z:d(c.rotateZ||c.rotate)},scale:d(c.scale,1),el:a};a.id||(a.id="step-"+(b+1));e["impress-"+a.id]=c;m(a,{position:"absolute",transform:"translate(-50%,-50%)"+D(c.translate)+E(c.rotate)+(" scale("+c.scale+") "),transformStyle:"preserve-3d"})},H=function(a){"number"===typeof a?a=0>a?k[k.length+a]:k[a]:"string"===typeof a&&(a=b.getElementById(a));return a&&
a.id&&e["impress-"+a.id]?a:null},G=null,v=function(a,b){if(!C||!(a=H(a)))return!1;h.scrollTo(0,0);var c=e["impress-"+a.id];l&&(l.classList.remove("active"),q.classList.remove("impress-on-"+l.id));a.classList.add("active");q.classList.add("impress-on-"+a.id);var c={rotate:{x:-c.rotate.x,y:-c.rotate.y,z:-c.rotate.z},translate:{x:-c.translate.x,y:-c.translate.y,z:-c.translate.z},scale:1/c.scale},g=c.scale>=r.scale;b=d(b,t.transitionDuration);var f=b/2;a===l&&(u=F(t));var k=c.scale*u;l&&l!==a&&y===l&&
(z(l,"impress:stepleave"),y=null);m(n,{perspective:t.perspective/k+"px",transform:" scale("+k+") ",transitionDuration:b+"ms",transitionDelay:(g?f:0)+"ms"});m(p,{transform:E(c.rotate,!0)+D(c.translate),transitionDuration:b+"ms",transitionDelay:(g?0:f)+"ms"});if(r.scale===c.scale||r.rotate.x===c.rotate.x&&r.rotate.y===c.rotate.y&&r.rotate.z===c.rotate.z&&r.translate.x===c.translate.x&&r.translate.y===c.translate.y&&r.translate.z===c.translate.z)f=0;r=c;l=a;h.clearTimeout(G);G=h.setTimeout(function(){var a=
l;y!==a&&(z(a,"impress:stepenter"),y=a)},b+f);return a};n.addEventListener("impress:init",function(){k.forEach(function(a){a.classList.add("future")});n.addEventListener("impress:stepenter",function(a){a.target.classList.remove("past");a.target.classList.remove("future");a.target.classList.add("present")},!1);n.addEventListener("impress:stepleave",function(a){a.target.classList.remove("present");a.target.classList.add("past")},!1)},!1);n.addEventListener("impress:init",function(){var a="";n.addEventListener("impress:stepenter",
function(c){h.location.hash=a="#/"+c.target.id},!1);h.addEventListener("hashchange",function(){h.location.hash!==a&&v(b.getElementById(h.location.hash.replace(/^#\/?/,"")))},!1);v(b.getElementById(h.location.hash.replace(/^#\/?/,""))||k[0],0)},!1);q.classList.add("impress-disabled");return w["impress-root-"+f]={init:function(){if(!C){var c=a("meta[name='viewport']")||b.createElement("meta");c.content="width=device-width, minimum-scale=1, maximum-scale=1, user-scalable=no";c.parentNode!==b.head&&(c.name=
"viewport",b.head.appendChild(c));c=n.dataset;t={width:d(c.width,1024),height:d(c.height,768),maxScale:d(c.maxScale,1),minScale:d(c.minScale,0),perspective:d(c.perspective,1E3),transitionDuration:d(c.transitionDuration,1E3)};u=F(t);[].slice.call(n.childNodes).forEach(function(a){p.appendChild(a)});n.appendChild(p);b.documentElement.style.height="100%";m(q,{height:"100%",overflow:"hidden"});c={position:"absolute",transformOrigin:"top left",transition:"all 0s ease-in-out",transformStyle:"preserve-3d"};
m(n,c);m(n,{top:"50%",left:"50%",perspective:t.perspective/u+"px",transform:" scale("+u+") "});m(p,c);q.classList.remove("impress-disabled");q.classList.add("impress-enabled");k=g(".step",n);k.forEach(A);r={translate:{x:0,y:0,z:0},rotate:{x:0,y:0,z:0},scale:1};C=!0;z(n,"impress:init",{api:w["impress-root-"+f]})}},"goto":v,next:function(){var a=k.indexOf(l)+1,a=a<k.length?k[a]:k[0];return v(a)},prev:function(){var a=k.indexOf(l)-1,a=0<=a?k[a]:k[k.length-1];return v(a)}}}).supported=B})(document,window);
(function(b,h){var p=function(b,d){var a=null;return function(){var g=this,h=arguments;clearTimeout(a);a=setTimeout(function(){b.apply(g,h)},d)}};b.addEventListener("impress:init",function(m){var d=m.detail.api;b.addEventListener("keydown",function(a){(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&40>=a.keyCode)&&a.preventDefault()},!1);b.addEventListener("keyup",function(a){if(!(a.shiftKey||a.altKey||a.ctrlKey||a.metaKey)&&(9===a.keyCode||32<=a.keyCode&&34>=a.keyCode||37<=a.keyCode&&
40>=a.keyCode)){switch(a.keyCode){case 33:case 37:case 38:d.prev();break;case 9:case 32:case 34:case 39:case 40:d.next()}a.preventDefault()}},!1);b.addEventListener("click",function(a){for(var g=a.target;"A"!==g.tagName&&g!==b.documentElement;)g=g.parentNode;if("A"===g.tagName){var h=g.getAttribute("href");h&&"#"===h[0]&&(g=b.getElementById(h.slice(1)))}d["goto"](g)&&(a.stopImmediatePropagation(),a.preventDefault())},!1);b.addEventListener("click",function(a){for(var g=a.target;(!g.classList.contains("step")||
g.classList.contains("active"))&&g!==b.documentElement;)g=g.parentNode;d["goto"](g)&&a.preventDefault()},!1);b.addEventListener("touchstart",function(a){if(1===a.touches.length){var b=a.touches[0].clientX,p=.3*h.innerWidth,m=null;b<p?m=d.prev():b>h.innerWidth-p&&(m=d.next());m&&a.preventDefault()}},!1);h.addEventListener("resize",p(function(){d["goto"](b.querySelector(".step.active"),500)},250),!1)},!1)})(document,window);
