/*jshint ignore:start*/
var txt;if(location.hash)document.getElementById("foo").value=location.hash.slice(1);else if(txt=localStorage.getItem("lcltext"))document.getElementById("foo").value=txt;
function parseCstm(a){document.getElementById("a").value=a;a=a.split(";");document.getElementById("1").style.backgroundColor=a[0];document.getElementById("2").style.backgroundColor=a[1];document.getElementById("q").style.backgroundColor=a[2];document.getElementById("r").style.backgroundColor=a[3];document.getElementById("d").style.backgroundColor=a[4];document.getElementById("h").style.backgroundColor=a[5];document.body.style.color=a[6]}var gd;(gd=localStorage.getItem("hmtltseter"))&&parseCstm(gd);
var t=!1,hide;function toggleRemove(){var a=document.getElementById("q"),b=document.getElementById("d"),c=document.getElementById("h");t?(a.style.right=17,b.style.opacity=0,c.style.opacity=0,hide=setTimeout(function(a){b.style.display=c.style.display="none"},1E3),t=!1):(b.style.display=c.style.display="block",a.style.right=87,clearTimeout(hide),b.style.opacity=1,c.style.opacity=1,t=!0)}
function removeLocalTextarea(){document.getElementById("foo").value="";localStorage.removeItem("lcltext");location.reload()}function removeLocals(){document.getElementById("foo").value="";localStorage.removeItem("lcltext");localStorage.removeItem("hmtltseter");localStorage.removeItem("mnuul");location.reload()}String.prototype.splice||(String.prototype.splice=function(a,b,c){return this.slice(0,a)+c+this.slice(a+Math.abs(b))});document.title="HTML Tester";var foo=document.getElementById("foo");
foo.onkeydown=function(a){setTimeout(function(){localStorage.setItem("lcltext",foo.value)},100);"Tab"==a.key&&(a.preventDefault(),foo.value=foo.value.splice(a=foo.selectionStart,0,"    "),foo.selectionStart=foo.selectionEnd=a+4)};
function test(){document.getElementById("q");var a=foo.value,b;try{preWindow.location.host}catch(c){b=c&&!1}"undefined"===typeof b&&(b=!0);window.preWindow&&!window.preWindow.closed&&b||(window.preWindow=open());window.preWindow.document.open();window.preWindow.document.write(a);window.preWindow.document.close();a||(window.preWindow.location="/dogrolld");window.preWindow.focus();window.onfocus=function(){foo.select()}}mnu=!1;
function openMenu(){document.getElementById("instructions").innerHTML="Status;Title;Test;Remove;Trash;Locals;";localStorage.setItem("mnuul",!0);var a=document.getElementsByClassName("title")[0].style;a.height="50%";a.fontSize="3vw";a.alignItems="flex-start";a.justifyContent="flex-end";a.padding="10";a.top="30px";document.getElementById("a").style.display="block";mnu=!0}function toggleMenu(){mnu?closeMenu():localStorage.getItem("mnuul")&&openMenu()}
function closeMenu(){if(mnu){var a=document.getElementsByClassName("title")[0].style;a.height="20%";a.fontSize="6vw";a.alignItems="center";a.justifyContent="center";a.padding="0";a=document.getElementById("a");a.style.display="none";a.value&&(parseCstm(a.value),localStorage.setItem("hmtltseter",a.value));mnu=!1}}var recognition=new webkitSpeechRecognition;recognition.onresult=function(a){"they're taking the Hobbits to Isengard"==a.results["0"]["0"].transcript&&openMenu()};recognition.start();
/*jshint ignore:end*/
